[package]
name = "leet"
version = "0.1.0"
edition = "2021"

[lib]
name = "solutions"
path = "src/solutions/lib.rs"

[[bin]]
name = "debugging"
path = "src/debug/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
